name: Destroy
description: Destroy infrastructure via Terraform
inputs:
  aws-key-id:
    description: "AWS access key ID for S3 backend"
    required: true
  aws-secret-access-key:
    description: "AWS secret access key for S3 backend"
    required: true
  terraform-dir:
    description: "Directory containing Terraform configuration"
    required: true
    default: "."
runs:
  using: composite
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ inputs.aws-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: eu-west-2
        mask-aws-account-id: true

    - name: Terraform init
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}
      run: terraform init -input=false

    - name: Terraform fmt -check
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}
      run: terraform fmt -check

    - name: Terraform validate
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}
      run: terraform validate

    - name: Terraform destroy
      shell: bash
      working-directory: ${{ inputs.terraform-dir }}
      run: terraform destroy -auto-approve
